Setup File
2023-gpig-a/Classifiers pull request #4
Opened 2023-12-12 21:23 UTC by BabarKhanDev

Add script to download and extract the COCO dataset into Datasets/coco/

Only tested on macOS but I see no reason why it won't work on Windows or Linux

2023-12-13 01:31 UTC, Laura7089 commented
Could probably use a shell shebang at the top:

```bash
!#/bin/sh
set -eux
```

2023-12-14 09:16 UTC, markspolakovs commented on setup.sh
> +cd images
Nitpick/suggestion:

```suggestion
mkdir -p Datasets/coco/images
cd Datasets/coco/images
```

2024-02-04 16:11 UTC, Laura7089 requested changes
Instead of duplicating the commands 4 times for each dataset download, you could use a for loop + array of URLs and/or a function to download and extract them.

It will work without (so long as you fix the shebang issue).

2024-02-04 16:11 UTC, Laura7089 commented on setup.sh
> +!#/bin/sh
My bad, this should be `#!/bin/sh`.

2024-02-04 16:19 UTC, markspolakovs approved these changes
Untested but code LGTM

2024-02-05 00:10 UTC, Laura7089 approved these changes

2024-02-05 00:10 UTC, merged